Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2024-04, with the labels that each got.

#127 Update to SD-JWT lib v0.3.0.
  gradle/libs.versions.toml
Labels: dependencies

#128 Group and limit dependabot PRs.
  .github/dependabot.yml
Labels: feature, dependencies

#132 Updated credential offer URI creation
  build.gradle.kts
  gradle.properties
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/CreateCredentialsOffer.kt
  src/main/resources/application.properties
Labels: feature

#137 Add support for JwtProofs using did:key and did:jwk.
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DefaultExtractJwkFromCredentialKey.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ResolveDidUrl.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ResolveDidUrlTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProofTest.kt
Labels: feature

#139 Adding support for DPoP.
  README.md
  build.gradle.kts
  docker-compose/docker-compose.yaml
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPConfigurationProperties.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenAuthentication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenError.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenReactiveAuthenticationManager.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenServerAccessDeniedHandler.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenServerAuthenticationEntryPoint.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/ServerDPoPAuthenticationTokenAuthenticationConverter.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidData.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromAuthServer.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/AuthorizationContext.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/main/resources/application.properties
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/GetMobileDrivingLicenceDataMockTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicenceTest.kt
Labels: feature

#143 Authorization server metadata and DPoP fixes.
  README.md
  docker-compose/docker-compose.yaml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Labels: bug

#146 Fix gradle-build-action
  .github/workflows/ci.yml
  .github/workflows/publish-to-container-registry.yml
Labels: dependencies, gitub action

#149 Fix mso_mdoc proof signing supported algs to EC
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
Labels: bug

#150 Update SD-JWT lib to v0.3.1
  gradle/libs.versions.toml
Labels: dependencies

#151 Add the ability to load a key-pair from a keystore, for SD-JWT signing.
  README.md
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/resources/application-keystore.properties
  src/main/resources/sd-jwt.jks
Labels: feature
