Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2024-11, with the labels that each got.

#229 DPoP: Resource-Server provided Nonce
  README.md
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPNonce.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPNonceWebFilter.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenError.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenReactiveAuthenticationManager.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenServerAccessDeniedHandler.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPTokenServerAuthenticationEntryPoint.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/ServerDPoPAuthenticationTokenAuthenticationConverter.kt
  src/main/resources/application.properties
Labels: feature

#235 Implement self-authenticating CNonce values using Encrypted JWTs.
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/credential/DecryptCNonceWithNimbusAndVerify.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/credential/GenerateCNonceAndEncryptWithNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/JWKExtensions.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofs.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/persistence/InMemoryCNonceRepository.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/IssueSpecificCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/credential/GenerateCNonce.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/credential/VerifyCNonce.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/LoadCNonceByAccessToken.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/UpsertCNonce.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProofTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofTest.kt
Labels: feature

#240 Remove c_nonce_expires_in
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptCredentialResponseWithNimbusTest.kt
Labels: enchancement

#245 Fix SD-JWT-VC issuer metadata
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/MetaDataApi.kt
Labels: bug

#248 Add some missing environment variable in docker-compose.yaml
  docker-compose/docker-compose.yaml
Labels: other
