Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2024-09, with the labels that each got.

#213 Remove CWT Proofs
  README.md
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateCwtProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialConfiguration.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofTest.kt
Labels: openid4vci draft 14

#212 Upgrade to waltid-mdoc-credentials-jvm 0.6.0
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/DefaultEncodeMobileDrivingLicenceInCbor.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/DefaultEncodePidInCbor.kt
Labels: dependencies

#215 Fully align SD-JWT-VC metadata
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
Labels: bug

#216 Draft14 - Batch Issuance
  README.md
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/MetaDataApi.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/credential/DefaultResolveCredentialRequestByCredentialIdentifier.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/persistence/InMemoryDeferredCredentialRepository.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/persistence/InMemoryIssuedCredentialRepository.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/HandleNotificationRequest.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/IssueSpecificCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/credential/ResolveCredentialRequestByCredentialIdentifier.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/LoadDeferredCredentialByTransactionId.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/LoadIssuedCredentialsByNotificationId.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/StoreDeferredCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/StoreIssuedCredentials.kt
  src/main/resources/application.properties
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptCredentialResponseWithNimbusTest.kt
Labels: feature, openid4vci draft 14, spec alignment
