Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2024-06, with the labels that each got.

#177 Update waltid mso library to v0.3.1
  gradle/libs.versions.toml
Labels: dependencies, bug

#186 Change docType & namespace for PID
  README.md
  docker-compose/keycloak/realms/pid-issuer-realm-realm.json
  http-client.env.json
  pid-issuer.http
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/PidCmnMeta.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Labels: bug

#184 Support CWT proofs
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateCwtProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProof.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialConfiguration.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/JwtVcJsonProfile.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/MsoMdocProfile.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/SdJwtVcProfile.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateJwtProofTest.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/ValidateProofTest.kt
Labels: feature

#187 Enable CWT proofs for PID in mso_mdoc
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
Labels: feature
