Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2025-09, with the labels that each got.

#406 Rename key attestation JWT type to key-attestation+jwt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/VerifyKeyAttestation.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/KeyAttestationJWT.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/OpenId4VciSpec.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Labels: openid4vci draft 16

#408 Bump Sonarqube scan GitHub action to 5.3.1
  .github/workflows/sonar.yml
Labels: github_actions

#410 Improve reliability and maintainability
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/security/DPoPNonceWebFilter.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DefaultExtractJwkFromCredentialKey.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/KeyAttestationJWT.kt
  src/main/resources/templates/generate-credentials-offer-form.html
Labels: enchancement

#415 Implement encrypted credential requests
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/json/JsonSupport.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/CredentialIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetCredentialIssuerMetaData.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Labels: feature, spec alignment, openid4vci draft 16

#425 Deferred issuance request/response updates
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApi.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DecryptRequestWithNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/EncryptResponseWithNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/persistence/InMemoryDeferredCredentialRepository.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/OpenId4VciSpec.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/IssueSpecificCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/jose/EncryptDeferredResponse.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/LoadDeferredCredentialByTransactionId.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/persistence/StoreDeferredCredential.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Labels: openid4vci draft 17

#429 Remove JSON Schema from advertised SD-JWT VC Type Metadata
  src/main/resources/vct/ehic.json
  src/main/resources/vct/pid_arf18.json
Labels: other

#435 Remove `vctm` and `vct#integrity` from issued EHICs VCs
  README.md
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/EncodeEuropeanHealthInsuranceCardInSdJwtVc.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/IssueSdJwtVcEuropeanHealthInsuranceCard.kt
Labels: other, spec alignment

#437 Improve error handling during Credential Request/Deferred Credential Request decryption
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/DecryptRequestWithNimbus.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/GetDeferredCredential.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/IssueCredential.kt
Labels: bug, enchancement
