Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2025-05, with the labels that each got.

#333 Replace sonarqube plugin with github actions
  .github/workflows/sonar.yml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: github_actions, enchancement

#321 Update SD-JWT PID per ARF v1.8
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/oauth/Claims.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/DefaultEncodePidInCbor.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromAuthServer.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/Pid.kt
  src/test/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/WalletApiTest.kt
Labels: other, spec alignment

#338 Upgrade dependency check plugin to 12.1.1
  gradle/libs.versions.toml
Labels: other

#347 Upgrade dependency eudiSdJwt to 0.13.1
  gradle/libs.versions.toml
Labels: dependencies

#351 Replace Spring Dependency Management plugin with Spring Boot BOM.
  build.gradle.kts
Labels: bug

#349 Introduce a new API to retrieve Type Metadata
  README.md
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/input/web/MetaDataApi.kt
  src/main/resources/application.properties
  src/main/resources/vct/pid_arf18.json
Labels: feature
