Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2025-03, with the labels that each got.

#308 Add missing `trust_anchor` PID attribute in metadata.
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
Labels: bug

#309 Merges changes from v0.3.5
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
Labels: other

#311 Support Status List Tokens in SD-JWT VC PIDs.
  README.md
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/EncodePidInSdJwtVc.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/status/GenerateStatusListTokenWithExternalService.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/domain/Types.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/out/status/GenerateStatusListToken.kt
  src/main/resources/application.properties
Labels: feature

#314 Upgrade gradlew
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies
