Repository eu-digital-identity-wallet/eudi-srv-pid-issuer, pull requests merged in 2025-07, with the labels that each got.

#369 Add missing claims in Type Metadata of EHIC
  src/main/resources/vct/ehic.json
Labels: bug

#372 Update Credential Displays. Include format as well.
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/IssueSdJwtVcEuropeanHealthInsuranceCard.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/mdl/IssueMobileDrivingLicence.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueMsoMdocPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/IssueSdJwtVcPid.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/PidCmnMeta.kt
Labels: other

#374 Fix Json Schema for `nationalities`. The shared array can be empty.
  src/main/resources/vct/pid_arf18.json
Labels: bug

#375 Update EHIC labels.
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/ehic/IssueSdJwtVcEuropeanHealthInsuranceCard.kt
Labels: other

#379 Drop Keycloak Admin Client
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/pid/GetPidDataFromKeyCloak.kt
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/qr/DefaultGenerateQrCode.kt
Labels: feature, other

#355 Add proxy settings for WebClient
  README.md
  src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt
  src/main/resources/application.properties
Labels: feature

#388 Enable passkeys support in Keycloak
  docker-compose/docker-compose.yaml
  docker-compose/keycloak/realms/pid-issuer-realm-realm.json
Labels: feature, other, enchancement
